cc = gcc
PORT=52737
CFLAGS = -std=c99 -Wall -Werror
CFLAGS+= -DPORT=\$(PORT) 

all: questions.c qtree.c mismatch_server_utils.c mismatch_server.c 
	$(CC) $(CFLAGS) questions.c qtree.c mismatch_server_utils.c mismatch_server.c -o mismatch_server
    
clean:  
	rm mismatch_server 
